name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  perform_ci:
    name: Execute CI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run unit-test
        run: python3 test_parse.py
